# Generated by Django 4.2.13 on 2024-06-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=55)),
                ('heslo', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Študent',
                'verbose_name_plural': 'Študenti',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=55)),
                ('heslo', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Učiteľ',
                'verbose_name_plural': 'Učitelia',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=155)),
                ('popis', models.TextField()),
                ('dostupnost', models.CharField(max_length=10)),
                ('pocet_konzultacii', models.IntegerField()),
                ('konzultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.ucitel')),
                ('odbor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.odbor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.student')),
            ],
        ),
    ]
