# Generated by Django 5.0.3 on 2024-06-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostupnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Dostupnosť',
                'verbose_name_plural': 'Dostupnosť',
            },
        ),
        migrations.AlterModelOptions(
            name='odbor',
            options={'verbose_name': 'Odbor', 'verbose_name_plural': 'Odbory'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name': 'Téma', 'verbose_name_plural': 'Témy'},
        ),
        migrations.AddField(
            model_name='student',
            name='trieda',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='heslo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tema',
            name='konzultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.ucitel'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tema',
            name='odbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.odbor'),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='heslo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.dostupnost'),
        ),
    ]
