# Generated by Django 5.0.3 on 2024-06-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_dostupnost_alter_odbor_options_alter_tema_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['dostupnost'], 'verbose_name': 'Téma', 'verbose_name_plural': 'Témy'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='trieda',
        ),
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='heslo',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.dostupnost'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='konzultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.ucitel'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='tema',
            name='odbor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.odbor'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='pocet_konzultacii',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='email',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='heslo',
            field=models.CharField(max_length=55),
        ),
    ]
